# Generated by Django 4.1.1 on 2022-10-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
