# Generated by Django 4.1.1 on 2022-09-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('travel_date_time', models.DateTimeField(blank=True, null=True)),
                ('luggage_quantity', models.IntegerField()),
            ],
        ),
    ]
